services:
  guardix-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
        - ./:/workspace
        - guardix-dev-vsc:/root/.vscode-server
    stdin_open: true
    tty: true

volumes:
  guardix-dev-vsc: